{{- if .Values.route.enabled -}}
{{- $fullName := include "aws_sandbox_metrics.name" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  namespace: {{ include "aws_sandbox_metrics.namespaceName" . }}
  labels:
    {{- include "aws_sandbox_metrics.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  path: /metrics
  host: ""
  port:
    targetPort: http
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
status:
  ingress: []
{{- end }}
