{{- if .Values.aws_sandbox_metrics_secrets.readonly -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-sandbox-readonly
  namespace: {{ include "aws_sandbox_metrics.namespaceName" . }}
  labels:
    {{- include "aws_sandbox_metrics.labels" . | nindent 4 }}
data:
  aws_access_key_id: {{ .Values.aws_sandbox_metrics_secrets.readonly.aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.aws_sandbox_metrics_secrets.readonly.aws_secret_access_key | b64enc }}
{{- end }}
